def COLOR_MAP = [
    'SUCCESS': 'good',
    'FAILURE': 'danger',
]

pipeline {
    agent any
    tools{
        maven "maven3"
        jdk "jdk8"
    }

    // Variables
    environment {
        cluster = 'vproprod'
        service = 'vpro-app-prod-svc'
    }

    stages{
        
        // Deploy to ECS cluster
        stage('Deploy image to ECS cluster PROD'){
            steps {
                withAWS(credentials: 'aws-creds', region: 'ap-south-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
        
    }

    post {
        always {
            echo 'Slack notifications.'
            slackSend channel: "#devopscicd",
                    color: COLOR_MAP[currentBuild.currentResult],
                    message: "**${currentBuild.currentResult}**: Job ${env.JOB_NAME} build: ${env.BUILD_NUMBER}. \n More info at ${env.BUILD_URL}"
        }
    }
}